# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/tmp/StartGm9767.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

from gvm.connections import SSHConnection
from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import (QWidget, QMainWindow, QMessageBox) 
from socket import gaierror


class Ui_StartForm(object):
    def setupUi(self, StartForm):
        StartForm.setObjectName("StartForm")
        StartForm.resize(501, 597)
        StartForm.setStyleSheet("background-color: rgb(32, 32, 32)")
        self.centralwidget = QtWidgets.QWidget(StartForm)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout.addLayout(self.verticalLayout_2)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setSizeConstraint(QtWidgets.QLayout.SetFixedSize)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout()
        self.verticalLayout_6.setSizeConstraint(QtWidgets.QLayout.SetFixedSize)
        self.verticalLayout_6.setSpacing(10)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.logo_label = QtWidgets.QLabel(self.centralwidget)
        self.logo_label.setMaximumSize(QtCore.QSize(200, 200))
        self.logo_label.setText("")
        self.logo_label.setPixmap(QtGui.QPixmap("Logos/Logo.png"))
        self.logo_label.setAlignment(QtCore.Qt.AlignCenter)
        self.logo_label.setObjectName("logo_label")
        self.verticalLayout_6.addWidget(self.logo_label, 0, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignTop)
        self.info_label = QtWidgets.QLabel(self.centralwidget)
        self.info_label.setMaximumSize(QtCore.QSize(250, 12))
        self.info_label.setStyleSheet("color: white")
        self.info_label.setObjectName("info_label")
        self.verticalLayout_6.addWidget(self.info_label, 0, QtCore.Qt.AlignHCenter)
        self.hostname_input = QtWidgets.QLineEdit(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.hostname_input.sizePolicy().hasHeightForWidth())
        self.hostname_input.setSizePolicy(sizePolicy)
        self.hostname_input.setStyleSheet("color: rgb(255, 255, 255);\n"
"border:  1px solid white")
        self.hostname_input.setAlignment(QtCore.Qt.AlignCenter)
        self.hostname_input.setObjectName("hostname_input")
        self.verticalLayout_6.addWidget(self.hostname_input, 0, QtCore.Qt.AlignHCenter)
        self.connect_button = QtWidgets.QPushButton(self.centralwidget)
        self.connect_button.clicked.connect(self.connect)
        self.connect_button.setMaximumSize(QtCore.QSize(200, 34))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.connect_button.setFont(font)
        self.connect_button.setStyleSheet("color: rgb(102, 196, 48) ;\n"
"border-width: 2px;\n"
"border-color: rgb(255, 255, 255);\n"
" ")
        self.connect_button.setObjectName("connect_button")
        self.verticalLayout_6.addWidget(self.connect_button, 0, QtCore.Qt.AlignHCenter)
        self.verticalLayout_3.addLayout(self.verticalLayout_6)
        self.horizontalLayout.addLayout(self.verticalLayout_3)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout.addLayout(self.verticalLayout)
        StartForm.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(StartForm)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 501, 22))
        self.menubar.setObjectName("menubar")
        StartForm.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(StartForm)
        self.statusbar.setObjectName("statusbar")
        StartForm.setStatusBar(self.statusbar)

        self.retranslateUi(StartForm)
        QtCore.QMetaObject.connectSlotsByName(StartForm)

    def retranslateUi(self, StartForm):
        _translate = QtCore.QCoreApplication.translate
        StartForm.setWindowTitle(_translate("StartForm", "MainWindow"))
        self.info_label.setText(_translate("StartForm", "Please enter the hostname of your GSM."))
        self.hostname_input.setPlaceholderText(_translate("StartForm", "Hostname"))
        self.connect_button.setText(_translate("StartForm", "Connect"))

    def connect(self):
        if self.hostname_input.text() != "":
            try:
                connection = SSHConnection(hostname=self.hostname_input.text())
                connection.connect()
            except gaierror:
                QMessageBox.about(QMainWindow(), "Error", "Wrong Hostname")
        else:
            QMessageBox.about(QMainWindow(), "Error", "Please enter a hostname")


